spring:
  application:
    name: delivery-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/delivery
    username: postgres
    password: seoght3658

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 19094
eureka:
  client:
    service-url:
      # 유레카 서버의 주소 설정
      defaultZone: http://localhost:19090/eureka/