spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth
    username: subinny
    password: mypassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      username: myuser
      password: mypassword

server:
  port: 19093
eureka:
  client:
    service-url:
      # 유레카 서버의 주소 설정
      defaultZone: http://localhost:19090/eureka/

key:
  company: "2GqvqTPM9dSZJdQ+anHou9m7b38qCEF0axdUOPEq5KSkxnU6jvsLdr9M6fIEmEjDEChwoYJQp30ncDE+9j/9lA=="
  hub_manager: "JCDyV/ev+0w3cFCngIENAb4fp0RR9Rgv2hdRkblR5IXZIJqrPm5O0ZYW6JQw7Fe33M62XOLfASuCaulhOFpr7w=="
  delivery_person: "xkCGI24PFPduZS9MBevxXFjl2Ku5FsDP3Z+zHfOjP5f0c93DM9u8Fh9dBm9z0bX8Iidpgx2IChp/J2sbAbSJPg=="
  master: "0mE0z5IT4fXZn7GRPONsz+Vmeev/SyYElEulSCxaQX5gwzPLg1BeAqdAT0t7ZkenMRG6qFGJozQpJAnV0wDM1A=="
#  hub_delivery: "bKAHEn//e7KHAot0RVVz2XfApMT4T03Pc2va19axqv4kw/sG0a0e0Z5aCLTRzZQHImhEVzKEyL9Ris5gDLksCA=="